stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

maven_build:
  stage: build
  image: maven:3.8.4-openjdk-11
  script:
    - mvn clean package -B
  artifacts:
    paths:
      - target/*.jar

test_login:
  stage: test
  image: maven:3.8.4-openjdk-11
  script:
    - mvn test -B

