image: maven:latest
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode"

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository/
    - target/

Build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

upload-course:
  stage: test
  script:
    - mvn -Dtest=CourseUploadTest.testCourseUpload test

