
image: maven:latest

stages:
  - build
  - test


variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"


cache:
  paths:
    - .m2/repository/
    - target/

Registration:
  stage: test
  script:
      - mvn -Dtest=com.swt_II.elearningplatform.RegistrationTest test

maven_build:
  stage: build
  script:
    - mvn clean compile -B
  artifacts:
    paths:
      - target/*.jar

maven_test:
  stage: test
  script:
    - mvn test