
image: maven:latest

stages:
  - build
  - test


variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

maven_build:
  stage: build
  script:
    - mvn clean compile -B
  artifacts:
    paths:
      - target/*.jar

maven_test:
  stage: test
  script:
    - mvn test